main:
  - name: Suggestion/Feedback
    identifier: support
    weight: 100
    url: https://github.com/creatoy
    params:
      header: My github home page.
      icon:
        vendor: font-awesome-solid
        name: headset

  - name: GitHub
    parent: support
    url: https://github.com/creatoy/my_site
    weight: 1
    params:
      icon:
        vendor: fab
        name: github
      description: This site repo.

  - name: Discussion
    parent: support
    url: https://github.com/creatoy/my_site/discussions
    weight: 2
    params:
      icon:
        vendor: font-awesome-regular
        name: comments
        color: green
      description: Ask questions or share your ideas.

  - name: Bug feedback
    parent: support
    url: https://github.com/creatoy/my_site/issues/new
    weight: 3
    params:
      icon:
        vendor: font-awesome-solid
        name: bug
        color: red
      description: Issue a bug or error.
